### ISSUE TITLE
Readme.md inconsistent

### ISSUE THREAD

**Issue by hartenthaler** [reteP-riS/HistoricEvents-Germany#1]
```
Resulting GEDCOM lines
1 EVEN Beginn des Ersten Weltkriegs
2 TYPE Historisches Ereignis
2 DATE 28 JUL 1914
2 NOTE Beginn des Ersten Weltkriegs durch die Kriegserklärung Österreich-Ungarns an Serbien.
2 SOUR https://de.wikipedia.org/wiki/Erster_Weltkrieg
```
This is not consistent with the code shown in the part "Implementation" using PLAC.

btw: I'm not sure if it is a good idea to use PLAC in historic events. On the one hand side it helps to understand where an event happened, on the other side everybody has is own structure of location data in a webtrees database and the structure in the historic data modules will not fit these existing structure.

**Comment by reteP-riS** [comment]
Thanks for paying attention. I updated that section as well.

With regard to your comment about using PLAC tags in historic events, please understand I currently do not actively promote this module because I am still evaluating the pro's and con's of the currently available features for myself to create something like a blueprint. The respective discussions on the webtrees forum make me believe that the individual needs - which events, which type, which sources, which languages, etc. - are so different that a completely different solution will be required long term to satisfy all or at least most of them.

Nevertheless your feedback is very much appreciated.
