### ISSUE TITLE
Invalid datetime format

### ISSUE THREAD

**Issue by feedhopper** [reteP-riS/HistoricEvents-Germany#2]
I have just set  up Webtrees, imported a ged file from MyHeritage and installed this plugin. When I try activating or deactivating it, I get this:

```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x87\xA9\xF0\x9F...' for column `d03be594`.`wt_session`.`session_data` at row 1 (SQL: update `wt_session` set `session_data` = initiated|b:1;_GUEST_sessiontime|s:10:"1674736188";language|s:2:"de";theme|s:7:"_argon_";CSRF_TOKEN|s:32:"JQZdTAX4RGxMvGvRvN2uYczW1KfVA0Cl";captcha-t|d:1674736196.5323469638824462890625;captcha-x|s:32:"8a29ce7b163946309c84d2143e64874e";captcha-y|s:32:"2893fbe006114632a3dfaf62e5fc4ce5";captcha-z|s:32:"7f5d8549e54a47f89137c7cc84c92e47";wt_user|i:1;flash_messages|a:2:{i:0;O:8:"stdClass":2:{s:4:"text";s:68:"Das Modul “Historic Events: Germany 🇩🇪” wurde deaktiviert.";s:6:"status";s:7:"success";}i:1;O:8:"stdClass":2:{s:4:"text";s:51:"Die Einstellungen der Webseite wurden aktualisiert.";s:6:"status";s:7:"success";}} where `session_id` = 3b5458048bb7d349ebe6df71c46d0a96) …/vendor/illuminate/database/Connection.php:712
#0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback('update `wt_sess...', Array, Object(Closure))
#1 …/vendor/illuminate/database/Connection.php(533): Illuminate\Database\Connection->run('update `wt_sess...', Array, Object(Closure))
#2 …/vendor/illuminate/database/Connection.php(466): Illuminate\Database\Connection->affectingStatement('update `wt_sess...', Array)
#3 …/vendor/illuminate/database/Query/Builder.php(3063): Illuminate\Database\Connection->update('update `wt_sess...', Array)
#4 …/app/SessionDatabaseHandler.php(125): Illuminate\Database\Query\Builder->update(Array)
#5 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('3b5458048bb7d34...', 'initiated|b:1;_...')
#6 …/app/Session.php(100): session_write_close()
#7 …/app/Http/Middleware/UseSession.php(80): Fisharebest\Webtrees\Session::save()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#19 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#20 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#34 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#35 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#36 {main}
```

Do you have any idea of what's happening?

Would love to use historic events...

Best

**Comment by reteP-riS** [comment]
I *believe* this issue is not or only indirectly related to this module. In the first line of this error message you'll find 2 pieces of information:

1. SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x87\xA9\xF0\x9F...' for column `d03be594`.`wt_session`.`session_data` at row 1 (SQL: update `wt_session` set `session_data` = ...
2. flash_messages|a:2:{i:0;O:8:"stdClass":2:{s:4:"text";s:68:"**Das Modul “Historic Events: Germany ????” wurde deaktiviert.**";s:6:"status";s:7:"**success**";}i:1;O:8:"stdClass":2:{s:4:"text";s:51:"**Die Einstellungen der Webseite wurden aktualisiert.**";s:6:"status";s:7:"**success**";}}

So the error seems to occur when webtrees tries to write session data to the database after the module was deactivated successfully. Maybe the database, the table `wt_session`, its column `session_data` or the database connection weren't set up correctly. Try searching the web for "Incorrect string value: '\xF0\x9F\x87\xA9\xF0\x9F...'"

Make sure you followed the installation instructions for this module exactly. If you unzip the module on your PC make sure to use the binary mode when transferring the files to the webserver.

There is one specific character in the module - the German flag which is represented by the ???? in your error message - but other historic modules use flags as well. So you could try to activate one of the other historic modules and see what happens. Or edit [line 39 of module.php](https://github.com/reteP-riS/HistoricEvents-Germany/blob/6ad513d11a82dc5df9ccc6c9ef0152551e3a5f21/module.php#L39), remove the flag and see what happens then. Let me know.

**Comment by feedhopper** [comment]
THANK YOU for getting back so quickly.

Your guess may be right since I do have this problem with one other plugin (german dates of wars).

Logging into the DB gives me this:

![image](https://user-images.githubusercontent.com/61922985/214859503-4cdb65ce-5232-4241-862f-7c2e437954f5.png)

Does it help in any way?

**Comment by reteP-riS** [comment]
The collations (utf8_unicode_ci) for all these tables seem to be correct. I am not so sure about the bottom line (utf8mb4_general_ci) because I have utf8_general_ci, but I *believe* that's not an issue.

In phpadmin click on the database server at the top of the screen. It should then show the database **connection** collation. I have utf8mb4_unicode_ci.

In phpadmin, in the list of tables click on wt_session, then on Structure. I have utf8_unicode_c for columns session_id and ip_address, but no entry in the collation column for the other fields.

As I have no detailed knowledge about this collation topic I suggest to collect all this information and open a thread at [https://www.webtrees.net/index.php/en/forum](https://www.webtrees.net/index.php/en/forum).

**Comment by feedhopper** [comment]
Hmm... 

![image](https://user-images.githubusercontent.com/61922985/214876947-0216dc78-732c-4e68-8948-623e70e0e801.png)

It's weird.

![image](https://user-images.githubusercontent.com/61922985/214877489-0621a176-8e8c-42d5-a2d3-204ca1d6c644.png)

**Comment by feedhopper** [comment]
Sorry, this is structure

![image](https://user-images.githubusercontent.com/61922985/214877909-fa0a7abd-b9b7-4945-bb62-11669ffa2c9d.png)

**Comment by reteP-riS** [comment]
So there is a difference for the session_data column, but I have no idea whether that might cause this issue. But it is obviously in the column that was mentioned in the error message. I have type:longblob, not type:longtext and no collation for that column.

What is your database product and your database version? What webtrees version are you using?

**Comment by reteP-riS** [comment]
Did you edit and (maybe accidentally) save the module.php file?

**Comment by reteP-riS** [comment]
Were you able to make some progress or even resolve the problem? Please update or close this issue.

**Comment by reteP-riS** [comment]
I herewith close this issue.
